name: Frontend-CI

on:
  workflow_dispatch: 
  push: 
    branches:   
      - main
        
jobs:   
  set_environment:    
    runs-on: ubuntu-latest
    # needs: demo 
    steps: 
      - name: Checkout code
        uses: actions/checkout@v2

      - name: "npm build"
        run: npm run build
